import { ClerkProvider } from '@clerk/nextjs'//for auth 
import { dark } from '@clerk/themes'
import { ThemeProvider } from '@/components/theme-provider'
// ThemeProvider relies on the context feature of React to pass the theme down to the components, 
// so you need to make sure that ThemeProvider is a parent of the components you are trying to customize.
import type { Metadata } from 'next'
// Next.js has a Metadata API that can be used to define your application metadata
// (e.g. meta and link tags inside your HTML head element) for improved SEO
import { Inter } from 'next/font/google' //font import
import './globals.css'

const inter = Inter({ subsets: ['latin'] }) //type of the font

export const metadata: Metadata = {
  title: 'Aletheia',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      {/* clerk used for auth and user management */}
    {/* setting base theme */}
      <html lang="en">
        <body className={inter.className}>
        {/* //font for whole body */}
          <ThemeProvider
            attribute='class' forcedTheme='dark' storageKey='aletheia-theme'>
            {children}
          </ThemeProvider>
              {/* //storageKey for local storage's name */}
        </body>
      </html>
    </ClerkProvider>
  )
}
